[package]
name = "bentobox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinyrand = "0.5.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
tinyrand-alloc = "0.5.0"

[[bench]]
name = "cri_mc"
harness = false
